version: '3.8'
services:
  api:
    build: .
    ports:
      - "8080:8080"  # Porta 8080 exposta para a API
    restart: always
    environment:
      JAVA_OPTS: "-Xms512m -Xmx512m"

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"  # Porta 8081 da máquina local para a porta 80 do contêiner
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api