spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
    username: rm553791
    password: 180298
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  listener:
    simple:
      prefetch: 1
  management:
    endpoints:
      web:
        exposure:
          include: health, info, metrics
      health:
        show-details: always

jwt:
  secret: suaChaveSecretaSuperSeguraComPeloMenos256BitsDeTamanho
  expiration: 3600000