spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
    username: rm553791
    password: 180298
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
jwt:
  secret: suaChaveSecretaSuperSeguraComPeloMenos512BitsDeTamanho
  expiration: 3600000  # 1 hora em milissegundos
